name: first-workflow

on:
  push:
    branches:
      - main

jobs:
  push-main:
    runs-on: ubuntu-latest
    steps:
      - name: Run on Push to Specific Branch
        run: echo "Pushed to main branch!"

