name : Secrets and variables
on : Workflow-dispatch
jobs : 
  Secrets :
    runs_on : ubuntu-latest
    steps :
      -name : calling secrets
       run : echo "my db password is ${{secrets.DB_PASSWORD}} and port is {{secrets.DB_Port}}"
 Variables : 
   runs-on : ubuntu-latest
   steps:
     -name : calling github variables 
      run : echo "my database name is ${{vars.DB_NAME}} and the username is ${{vars.DB_USER}}"
       
